<?php
/* * *************************************************************
 * Extension Manager/Repository config file for ext: "simpleaddress"
 *
 * Auto generated by Extension Builder 2015-04-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 * ************************************************************* */

$EM_CONF[$_EXTKEY] = array(
    'title'            => 'Simple-Address',
    'description'      => 'This extension offers an simple way for showing an address block with or without a Google Maps with. The address
will rendered in vCard format.',
    'category'         => 'plugin',
    'author'           => 'Steve Lenz',
    'author_email'     => 'kontakt@steve-lenz.de',
    'state'            => 'stable',
    'internal'         => '',
    'uploadfolder'     => '0',
    'createDirs'       => '',
    'clearCacheOnLoad' => 0,
    'version'          => '1.5.1',
    'constraints'      => array(
        'depends'   => array(
            'typo3'   => '6.2.0-7.6.99',
            'extbase' => '6.2.0-7.6.99',
            'fluid'   => '6.2.0-7.6.99',
        ),
        'conflicts' => array(
        ),
        'suggests'  => array(
        ),
    ),
);
